---
- name: Install Grafana
  hosts: main
  remote_user: ubuntu
  become: true

  tasks:
    - name: Download apt key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
    
    - name: Add Grafna repository to source.list
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
    
    - name: Update apt cache and Install Grafana
      ansible.builtin.apt:
        name: grafana
        update_cache: true
    
    - name: Install Grafana
      ansible.builtin.apt:
        name: grafana
        update_cache: true
        state: present 
        
    - name: Ensure Grafana is started and enabled
      ansible.builtin.systemd:
        name: grafana-server
        enabled: true
        state: started

